### ISSUE TITLE
npm install出现异常

### ISSUE THREAD

**Issue by xaviertung** [sorrycc/dva-boilerplate-isomorphic#2]
npm install安装无效，报错异常：npm ERR! cb() never called!，请问是npm版本有要求吗？我的当前npm版本：
$ npm -v 3.8.3

**Comment by sorrycc** [comment]
多试几遍就好了，我也遇到过。

**Comment by xaviertung** [comment]
我逐个包安装试了下，我的开发环境是windows系统，fsevents依赖包darwin不支持windows。
